version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ALIR
  - aliyuncs
  - apng
  - armv
  - bfsu
  - breaked
  - buildx
  - Cloneflags
  - devtmpfs
  - dockerenv
  - envconfig
  - errgroup
  - Fstype
  - geminilake
  - GITTAG
  - GOARCH
  - imagetools
  - inplace
  - iofs
  - KHTML
  - KMGTE
  - kubespider
  - ldflags
  - localtime
  - logfile
  - logsize
  - Mkdirs
  - modtime
  - mountinfo
  - nasxunlei
  - newname
  - NEWNS
  - noninteractive
  - nsynobios
  - oldname
  - PKGDEST
  - PKGNAME
  - PKGROOT
  - PKGVER
  - rdparty
  - realpath
  - resolv
  - rootfs
  - shenzhen
  - softprops
  - SYNO
  - synobios
  - synoinfo
  - synoman
  - SYNOPKG
  - SYNOPLATFORM
  - sysfs
  - TARGETARCH
  - testdata
  - tmpfs
  - trimpath
  - tzdata
  - ulikunitz
  - undos
  - wcgi
  - webman
  - webp
  - xunl
  - xunlei
  - zcvf
  - zoneinfo
ignoreWords: []
import: []
