version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
    - ALIR
    - aliyuncs
    - apng
    - armv
    - bfsu
    - breaked
    - buildx
    - Cloneflags
    - dockerenv
    - envconfig
    - errgroup
    - geminilake
    - GITTAG
    - GOARCH
    - inplace
    - iofs
    - KHTML
    - KMGTE
    - kubespider
    - ldflags
    - localtime
    - Mkdirs
    - modtime
    - mountinfo
    - nasxunlei
    - newname
    - NEWNS
    - noninteractive
    - nsynobios
    - oldname
    - PKGDEST
    - PKGNAME
    - PKGROOT
    - PKGVER
    - rdparty
    - realpath
    - resolv
    - rootfs
    - shenzhen
    - softprops
    - SYNO
    - synobios
    - synoinfo
    - synoman
    - SYNOPKG
    - SYNOPLATFORM
    - TARGETARCH
    - testdata
    - trimpath
    - tzdata
    - ulikunitz
    - wcgi
    - webman
    - webp
    - xunl
    - xunlei
    - zcvf
    - zoneinfo
ignoreWords: []
import: []
