name: 4.AcrBuild

on:
  workflow_dispatch:

jobs:
  AcrBuild:
    runs-on: ubuntu-latest
    steps:
      - name: 获取版本
        uses: dawidd6/action-download-artifact@v12
        with:
          name: version
          path: ./artifacts/
          workflow: 1.prepare.yml
          github_token: ${{secrets.GH_TOKEN}}

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GH_TOKEN }}"

      - name: 登录ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: 拉取推送
        run: |
          VERSION=$(cat ./artifacts/version)
          IMG_SRC=ghcr.io/cnk3x/xunlei:$VERSION
          IMG_DST=registry.cn-shenzhen.aliyuncs.com/cnk3x/xunlei:$VERSION
          docker buildx imagetools create -t $IMG_DST $IMG_SRC
          echo "验证清单："
          docker buildx imagetools inspect $IMG_DST
          echo "成功推送：$IMG_DST"
