name: DcrBuild

on:
  workflow_dispatch:

jobs:
  DcrBuild:
    runs-on: ubuntu-latest
    steps:
      - name: 获取版本
        uses: actions/download-artifact@v7
        with: { name: version, path: ./artifacts/version }

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GH_TOKEN }}"

      - name: 登录DCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DCR_USER }}
          password: ${{ secrets.DCR_TOKEN }}

      - name: 拉取推送
        run: |
          VERSION=$(cat ./artifacts/version)
          IMG_SRC=ghcr.io/cnk3x/xunlei:$VERSION
          IMG_DST=cnk3x/xunlei:$VERSION
          docker buildx imagetools create -t $IMG_DST $IMG_SRC
          echo "验证清单："
          docker buildx imagetools inspect $IMG_DST
          echo "成功推送：$IMG_DST"
